version: '3.8'

services:

  adminer:
    image: adminer
    depends_on:
      - test-db
      - test-db-test
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: marli-db
      ADMINER_DEFAULT_DB_NAME: marli
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8081:8080

  test-db:
    image: mysql:latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_LOCAL_DEV_PORT}:3306
    volumes:
      - mysql_bkp_dev:/var/lib/mysql

  test-db-test:
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
    ports:
      - 3311:3306

  test-api:
    build:
      context: ./.
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - 4301:4300
    stdin_open: true
    tty: true
    volumes:
      - ./.:/app/.
    depends_on:
      - test-db
      - test-db-test
volumes:
    mysql_bkp_dev:
